---
abstract: 'Convert to and from proquints'
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test2::V0: '0'
configure_requires:
  ExtUtils::MakeMaker::CPANfile: '0.09'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.64, CPAN::Meta::Converter version 2.150010'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Proquint
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Exporter::Tiny: '0'
  Socket: '2.022'
  perl: v5.13.2
  strict: '0'
  warnings: '0'
resources:
  repository: ssh://git@github.com/mlawren/p5-Proquint.git
version: v1.0.0_2
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
