---
abstract: 'Convert to and from proquints'
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test2::V0: '0'
configure_requires:
  ExtUtils::MakeMaker::CPANfile: '0.08'
  Pod::Text: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.0402, CPAN::Meta::Converter version 2.150001'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Proquint
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Exporter::Tiny: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  repository: https://github.com/mlawren/p5-Proquint
version: '0.003'
